services:
  - type: web
    name: naiom-backend
    runtime: docker
    region: frankfurt
    plan: free
    envVars:
      - key: LINKEDIN_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: INSTAGRAM_API_KEY
        sync: false
      - key: TIKTOK_API_KEY
        sync: false
      - key: CANVA_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: IDEOGRAM_API_KEY
        sync: false
      - key: MIDJOURNEY_API_KEY
        sync: false
